server:
  http:
    addr: 0.0.0.0:8002
    timeout: 100s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 100s
data:
  database:
    driver: postgresql
    source: postgresql://postgres:123456@localhost:5433/product
  redis:
    addr: 172.27.59.28:6379
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s
  rabbitmq:
    url: amqp://guest:guest@localhost:5672/
    queue: resource.instance.created
    exchange: resource.events
